//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee2
    {
        public Nullable<int> RecID { get; set; }
        [Required]
        [Display(Name="Employee ID")]
        public string EmpID { get; set; }
        [Display(Name = "Employee Name")]
        [Required]
        public string EName { get; set; }
        [Display(Name = "Employee Father Name")]
        [Required]
        public string EFName { get; set; }
        [Required]
        [Display(Name = "Employee Mother Name")]
        public string EMName { get; set; }
        [Display(Name = "Present Address")]
        public string MAdd1 { get; set; }
        [Display(Name = "Parmanet Address")]
        public string PAdd1 { get; set; }
        [Display(Name = "District Name")]
        public int DisID { get; set; }
        [Display(Name = "Thana Name")]
        public int ThaID { get; set; }
        [Display(Name = "Date of Bairth")]
        public DateTime DOB { get; set; }
        [Display(Name = "Contact Number 1")]
        public string ConNum1 { get; set; }
        [Display(Name = "Contact Number 2")]
        public string ConNum2 { get; set; }
        [Display(Name = "NID")]
        public string ENID { get; set; }
        [Display(Name = "Position ID")]
        public int PosID { get; set; }
        public int PID { get; set; }
        [Display(Name = "Joining Date")]
        public DateTime JDate { get; set; }

      
    }
}
