//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceStation
    {
        public int Id { get; set; }
        public Nullable<int> st { get; set; }
        public string InterStation { get; set; }
        public string SourceName1 { get; set; }
    }
}
