//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thana
    {
        public Nullable<int> DisID { get; set; }
        public int ThaID { get; set; }
        public string Name { get; set; }
        public string Entryby { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
    }
}
